services:

  db:
    image: ${DOCKER_DB_IMAGE}
    container_name: onlygirls-test-db
    restart: always
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
    ]
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      LANG: C.UTF_8
    networks:
      - www
    volumes:
      - db_data:/var/lib/mysql
      - ./configs/db-init:/docker-entrypoint-initdb.d

  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    container_name: onlygirls-test-app
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - path: ./app/.env
        required: true
      - path: ./.env
        required: false
    ports:
      - "5173:5173"
      - "8080:8080"
    depends_on:
      - db
      - db-api
    networks:
      - www

  db-api:
    build:
      context: ./db-api
      dockerfile: Dockerfile
    container_name: onlygirls-test-db-api
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - www
    env_file:
      - path: ./.env
        required: true
    volumes:
      - ./db-api:/usr/src/app

volumes:
  db_data:

networks:
  www:
